---
title: "Lab 4: Quiz Day"
subtitle: "APEC 1101 - Applied Economics, University of Minnesota"
author: "Shunkei Kakimoto"
format: 
  revealjs:
    embed-resources: false
    slide-number: c/t
    width: 1600
    height: 900
    theme: 
      - simple 
      - ../../z_slide_style/styles_large.scss
    fontsize: 1.8rem
    callout-icon: false
    scrollable: true
    echo: true
    multiplex: true
    code-link: true
    title-slide-attributes:
      data-background-color: "#447099"
    fig-dpi: 400
    chalkboard: true
    preview-links: false
---

## {.center}
### {{< fa list >}} Today's Outline {.center}

+ Problem 1 in Study Guide for Quiz I: Comparative Advantage
+ Quiz (25 minutes)

:::{.notes}
+ Today is a quiz day. Before the quiz, we will review the problem 1 in the Study Guide  because I received some questions about this problem.
+ Then, after that we will have a quiz.
:::



## Do you remember this problem? {.center}

We did this problem in last week's lab:

<br>

| Country | Steel (tons/day) | Textile (yds/day) |
|---------|--------------|----------------|
| Brazil  | 2            | 10              |
| Germany | 4            | 40              |

**Question**

Which country has a comparative advantage in producing Steel? Which country a comparative advantage in producing Textile?

<br>

:::{.fragment}
::: {.callout-important}
## Opportunity Cost of Producing a Unit of a Good
For example, opportunity cost of a unit of steel (one ton of steel) in Brazil is the amount of textile that Brazil must give up to produce one ton of steel.
:::
:::


:::{.notes}
+ We did this problem in the last week's lab to understand the concept of comparative advantage.
+ There are two countries Brazil and Germany, and they produce either steel or textile. The question is that which country should produce which good. In other words, ...
+ To solve this problem, we derived the opportunity cost of producing a unit of a good in each country.
  + For example, to determine which country has a comparative advantage in producing steel, we need to compare the opportunity costs of producing 1 ton of steel in each country.
  + In this case, Brazil can produce 2 tons of steel per day by giving up 10 yards of textile. So, the opportunity cost of producing 1 ton of steel in Brazil is 10/2 = 5 yards of textile.
  + Let's look at Germany next. 


+ [In this table, the productivity information is presented in terms of the quantity of a good that can be produced in a given amount of time. But it is not always the case. Sometimes the productivity information is presented in terms of the **time** required to produce a unit of a good.]{style="color: red;"}
:::


## Today's Problem: Problem 1 in Study Guide for Quiz I, modified

[Now the productivity information is presented in terms of ***the time required to produce a unit of a good***:]{style="color: #f57f17;"}

<br>

| Country | 1 Bushel of wheat | 1 T-shirt |
|---------|--------------|----------------|
| Canada  | 60 minutes            | 30 minutes              |
| Senegal | 5 hours            | 2 hours              |

**Questions**

a. Which country has a comparative advantage in wheat and why?
b. Which country has a comparative advantage in T-shirts and why?

<br>

:::{.fragment}
::: {.callout-important}
The basic idea is the same as the previous problem. For example, to determine the comparative advantage in wheat, we need to compare the opportunity costs of producing a unit of wheat (1b of wheat) in each country.
:::
:::


:::{.notes}
+ This table is such an example. This is the problem 1 in the Study Guide for Quiz I.
+ There are two countries Canada and Senegal, and they produce either wheat or T-shirt. Now, their productivity is presented in terms of the time required to produce a unit of a good.
+ Now, we need to be a little bit more careful. 
+ Here are the question. Which country has a comparative advantage in wheat and why?
+ Even though the productivity information is presented differently from the previous problem, the basic idea is the same. For example, 
:::


## Today's Problem: Problem 1 in Study Guide for Quiz I 

| Country | 1 Bushel of wheat | 1 T-shirt |
|---------|--------------|----------------|
| Canada  | 60 minutes            | 30 minutes              |
| Senegal | 5 hours            | 2 hours              |

**(a) Which country has a comparative advantage in wheat and why? Explain or illustrate.**

<br>

[Which country can produce 1b of wheat at a lower opportunity cost?]{.text-blue}

<br>

:::{.fragment .fade-up}
Canada can produce 1b of wheat in 60 minutes. With the same amount of time, Canada can produce 2 T-shirts. 

&rarr; Canada can produce 1b of wheat by giving up 2 T-shirts.

&rarr; Canada's opportunity cost of producing 1b of wheat is 2 T-shirts.
:::


<br>

:::{.fragment .fade-up}
[**What about Senegal?**]{.text-orange}
:::

## Today's Problem: Problem 1 in Study Guide for Quiz I 

| Country | 1 Bushel of wheat | 1 T-shirt |
|---------|--------------|----------------|
| Canada  | 60 minutes            | 30 minutes              |
| Senegal | 5 hours            | 2 hours              |


**(b) Which country has a comparative advantage in wheat and why? Explain or illustrate.**

:::{.fragment .fade-up}
Canada can produce 1 T-shirt in 30 minutes. With the same amount of time, Canada can produce 0.5b of wheat. 

&rarr; Canada can produce 1 T-shirt by giving up 0.5b of wheat.

&rarr; Canada's opportunity cost of producing 1 T-shirt is 0.5b of wheat.
:::

<br>

:::{.fragment .fade-up}
[**What about Senegal?**]{.text-orange}
:::


## Memos:


## Summary


+ To determine the comparative advantage in producing a good, we need to compare the opportunity costs of producing a unit of that good in each country.

<br>

+ When computing the opportunity cost, you want to pay close attention to [the form in which the productivity information is presented]{style="text-decoration: underline;"}.
  + quantity of a good that can be produced in a given amount of time (e.g. 2 tons/day)
  + time required to produce a unit of a good (e.g. 60 mins/1b of wheat)

<br>

+ [But the important thing is to understand the concept of opportunity cost.]{.text-red}
  + [**You calculate how much of the other good must be given up to produce a unit of the good.**]{.text-orange}
  + As long as you understand this concept, you will not be confused by the different forms of productivity information!